# 聊天列表
聊天.全局列表名称=global_chat
聊天.最大记录数=200
聊天.写入列表数据库=true
聊天.允许插件发送系统消息=true

# 进入退出
聊天.玩家进入广播=true
聊天.玩家退出广播=true

# 模板
模板.普通聊天={name}: {message}
模板.玩家进入=[lime]{name}[] 进入了服务器 {extra}
模板.玩家退出=[scarlet]{name}[] 离开了服务器
模板.系统消息=[accent]{message}[]

# 参数
参数.允许等级=true
参数.允许经济=true
参数.允许绑定状态=true
